// Compiler.h
// T# v2.0.0-beta1
// Dylan Armstrong, 2026

#pragma once

#include "TSharpBaseVisitor.h"
#include "TSharpParser.h"

#include "BytecodeFunction.h"
#include "BytecodeModule.h"
#include "Chunk.h"
#include "OpCode.h"
#include "Value.h"

#include <cstddef>
#include <cstdint>
#include <string>
#include <unordered_map>
#include <vector>

namespace tsharp {

// Compiler class for T#
// Inherits the base visitor generated by ANTLR
class Compiler final : public TSharpBaseVisitor {
  public:
	BytecodeModule compile(const std::vector<TSharpParser::ProgramContext*>& programs, TSharpParser::ProgramContext* entry_program);

	antlrcpp::Any visitBlock(TSharpParser::BlockContext* ctx) override;

	antlrcpp::Any visitVariableStatement(TSharpParser::VariableStatementContext* ctx) override;

	antlrcpp::Any visitVariableDecl(TSharpParser::VariableDeclContext* ctx) override;

	antlrcpp::Any visitAssignmentStatement(TSharpParser::AssignmentStatementContext* ctx) override;

	antlrcpp::Any visitAssignment(TSharpParser::AssignmentContext* ctx) override;

	antlrcpp::Any visitExpressionStatement(TSharpParser::ExpressionStatementContext* ctx) override;

	antlrcpp::Any visitExpression(TSharpParser::ExpressionContext* ctx) override;

	antlrcpp::Any visitLogicalOrExpression(TSharpParser::LogicalOrExpressionContext* ctx) override;

	antlrcpp::Any visitLogicalAndExpression(TSharpParser::LogicalAndExpressionContext* ctx) override;

	antlrcpp::Any visitEqualityExpression(TSharpParser::EqualityExpressionContext* ctx) override;

	antlrcpp::Any visitRelationalExpression(TSharpParser::RelationalExpressionContext* ctx) override;

	antlrcpp::Any visitAdditiveExpression(TSharpParser::AdditiveExpressionContext* ctx) override;

	antlrcpp::Any visitMultiplicativeExpression(TSharpParser::MultiplicativeExpressionContext* ctx) override;

	antlrcpp::Any visitUnaryExpression(TSharpParser::UnaryExpressionContext* ctx) override;

	antlrcpp::Any visitPostfixExpression(TSharpParser::PostfixExpressionContext* ctx) override;

	antlrcpp::Any visitPrimary(TSharpParser::PrimaryContext* ctx) override;

	antlrcpp::Any visitLiteral(TSharpParser::LiteralContext* ctx) override;

	antlrcpp::Any visitArrayLiteral(TSharpParser::ArrayLiteralContext* ctx) override;

	antlrcpp::Any visitIfStatement(TSharpParser::IfStatementContext* ctx) override;

	antlrcpp::Any visitWhileStatement(TSharpParser::WhileStatementContext* ctx) override;

	antlrcpp::Any visitDoWhileStatement(TSharpParser::DoWhileStatementContext* ctx) override;

	antlrcpp::Any visitForStatement(TSharpParser::ForStatementContext* ctx) override;

	antlrcpp::Any visitBreakStatement(TSharpParser::BreakStatementContext* ctx) override;

	antlrcpp::Any visitContinueStatement(TSharpParser::ContinueStatementContext* ctx) override;

	antlrcpp::Any visitSwitchStatement(TSharpParser::SwitchStatementContext* ctx) override;

	antlrcpp::Any visitReturnStatement(TSharpParser::ReturnStatementContext* ctx) override;

	antlrcpp::Any visitTryStatement(TSharpParser::TryStatementContext* ctx) override;

	antlrcpp::Any visitThrowStatement(TSharpParser::ThrowStatementContext* ctx) override;

  private:
	// Per-function compilation state
	void begin_scope();

	void end_scope();

	struct LocalInfo {
		size_t slot = 0;
		std::string type;
	};

	struct FunctionCompilerContext {
		BytecodeFunction* function = nullptr;

		std::vector<std::unordered_map<std::string, LocalInfo>> scopes;

		size_t next_local = 0;
	};

	// Loop/switch compilation state
	struct LoopCompilerContext {
		size_t continue_target = 0;

		std::vector<size_t> break_jumps;

		std::vector<size_t> continue_jumps;
	};

	// Main compiler state
	BytecodeModule module;

	BytecodeFunction* current_function = nullptr;

	ClassInfo* current_class = nullptr;

	std::vector<FunctionCompilerContext> function_contexts;

	std::vector<LoopCompilerContext> loop_contexts;

	// Top-level passes
	void declare_top_level(TSharpParser::ProgramContext* program);

	void compile_top_level(TSharpParser::ProgramContext* program);

	// Top-level declarations
	void declare_function(TSharpParser::FunctionDeclContext* ctx);

	void declare_class(TSharpParser::ClassDeclContext* ctx);

	void declare_interface(TSharpParser::InterfaceDeclContext* ctx);

	void declare_enum(TSharpParser::EnumDeclContext* ctx);

	void declare_global(TSharpParser::GlobalVarDeclContext* ctx);

	void compile_global_initializer(TSharpParser::GlobalVarDeclContext* ctx);

	// Class members
	void declare_method(size_t class_index, TSharpParser::MethodDeclContext* ctx);

	void declare_constructor(size_t class_index, TSharpParser::ConstructorDeclContext* ctx);

	void declare_property(size_t class_index, TSharpParser::PropertyDeclContext* ctx);

	// Function/class compilation
	void compile_function(TSharpParser::FunctionDeclContext* ctx);

	void compile_class(TSharpParser::ClassDeclContext* ctx);

	void compile_method(size_t class_index, TSharpParser::MethodDeclContext* ctx);

	void compile_constructor(size_t class_index, TSharpParser::ConstructorDeclContext* ctx, size_t constructor_index);

	void compile_property(size_t class_index, TSharpParser::PropertyDeclContext* ctx);

	// Function context helpers
	void begin_function(BytecodeFunction& function);

	void end_function();

	FunctionCompilerContext& current_context();

	Chunk& chunk();

	// Local/global/function/class resolution
	size_t declare_local(const std::string& name, const std::string& type = {});

	std::string resolve_local_type(const std::string& name) const;

	size_t declare_temporary();

	size_t resolve_local(const std::string& name) const;

	bool has_local(const std::string& name) const;

	size_t resolve_global(const std::string& name) const;

	size_t resolve_function(const std::string& name) const;

	size_t resolve_class(const std::string& name) const;

	// Bytecode emission
	void emit_opcode(OpCode opcode);

	void emit_byte(uint8_t value);

	void emit_u16(uint16_t value);

	void emit_constant(Value value);

	void emit_load_local(size_t slot);

	void emit_store_local(size_t slot);

	size_t emit_jump(OpCode opcode);

	void patch_jump(size_t operand_position);

	void emit_loop(size_t loop_start);

	// More complex emission helpers
	void emit_variable_load(const std::string& name);

	void emit_compound_operator(const std::string& op);

	void emit_string_operand(const std::string& value);

	void compile_call(const std::string& name, TSharpParser::ArgumentListContext* arguments);

	void compile_postfix_suffix(TSharpParser::PostfixSuffixContext* ctx);

	// Loop/switch helpers
	void begin_loop(size_t continue_target);

	void end_loop();

	void patch_continue_jumps(size_t target);

	void compile_switch_section(TSharpParser::SwitchSectionContext* ctx);

	// Utility helpers
	bool has_modifier(TSharpParser::ModifiersContext* ctx, const std::string& modifier) const;

	// Helpers referenced by Compiler.cpp but implemented elsewhere
	// or still needing implementation
	bool try_get_constant_expression(TSharpParser::ExpressionContext* expression, Value& value);

	bool is_builtin(const std::string& name) const;

	size_t resolve_native(const std::string& name) const;

	void register_natives();

	bool is_builtin_constant(const std::string& name) const;

	Value get_builtin_constant(const std::string& name) const;

	size_t emit_exception_handler_placeholder();

	void patch_exception_handler(size_t handler_position, size_t target);

	void patch_absolute_jump(size_t operand_position, size_t target);
};

}