// tsharp_listener.h
// Dylan Armstrong, 2026

#pragma once

#include <map>
#include <string>

#include "tsharp_parserBaseListener.h"

class tsharp_listener : public tsharp_parserBaseListener {
private:
    // Variable state in T# (of different types)
    std::map<std::string, int> ints;
    std::map<std::string, std::string> strings;
    std::map<std::string, bool> bools;
    std::map<std::string, char> chars;
    std::map<std::string, double> doubles;
    std::map<std::string, float> floats;
    std::map<std::string, short> shorts;
    std::map<std::string, long> longs;

public:
    // Constructor
    tsharp_listener();

    // Integer methods
    const int get_int(const std::string& index) const;
    void add_int(const std::string& index, const int value);

    // String methods
    const std::string get_string(const std::string& index) const;
    void add_string(const std::string& index, const std::string& value);

    // Floating point methods
    const float get_float(const std::string& index) const;
    void add_float(const std::string& index, const float value);
    
    // Listen for a println/print statement -> when heard, call the below methods (inherited from tsharp_parserBaseListener - which is generated by ANTLR)
    void enterPrintln_statement(tsharp_parser::Println_statementContext* ctx) override;
    void enterPrint_statement(tsharp_parser::Print_statementContext* ctx) override;
    
    // Listen for an entered assignment (inherited from tsharp_parserBaseListener - which is generated by ANTLR)
    void enterAssignment(tsharp_parser::AssignmentContext* ctx) override;

    // Math functions
    void enterSquare_root(tsharp_parser::Square_rootContext* ctx) override;
    void enterAbsolute_value(tsharp_parser::Absolute_valueContext* ctx) override;

    // Expressions
    void enterExpression(tsharp_parser::ExpressionContext* ctx) override;
};