// tsharp_listener.h
// Dylan Armstrong, 2026

#pragma once

#include <map>
#include <memory>
#include <string>

#include "tsharp_class.h"
#include "tsharp_function.h"
#include "tsharp_parser.h"
#include "tsharp_parserBaseListener.h"
#include "tsharp_types.h"

class tsharp_listener : public tsharp_parserBaseListener {
private:
	// Variable state in T# (of different types)
	std::map<std::string, int> ints;
	std::map<std::string, std::string> strings;
	std::map<std::string, bool> bools;
	std::map<std::string, char> chars;
	std::map<std::string, double> doubles;
	std::map<std::string, float> floats;
	std::map<std::string, short> shorts;
	std::map<std::string, long> longs;
	std::map<std::string, tsharp_function> functions;
	std::map<std::string, tsharp_class> classes;
	std::map<std::string, std::shared_ptr<tsharp_class>> objects;

	// Execution state
	bool executing;

	std::string remove_quotes_from_string(std::string& str) const;

public:
	// Constructor
	tsharp_listener();

	// Destructor
	~tsharp_listener();

	// Copy semantics
	tsharp_listener(const tsharp_listener&) = delete;
	tsharp_listener& operator=(const tsharp_listener&) = delete;

	// Integer methods
	const int& get_int(const std::string& index) const;
	void add_int(const std::string& index, const int value);

	// String methods
	const std::string& get_string(const std::string& index) const;
	void add_string(const std::string& index, const std::string& value);

	// Floating point methods
	const float& get_float(const std::string& index) const;
	void add_float(const std::string& index, const float value);

	// Listen for a println/print statement -> when heard, call the below methods (inherited from tsharp_parserBaseListener - which is generated by ANTLR)
	void enterPrintln_statement(tsharp_parser::Println_statementContext* ctx) override;
	void enterPrint_statement(tsharp_parser::Print_statementContext* ctx) override;

	// Listen for an entered assignment (inherited from tsharp_parserBaseListener - which is generated by ANTLR)
	void enterAssignment(tsharp_parser::AssignmentContext* ctx) override;

	// Math functions
	void enterSquare_root(tsharp_parser::Square_rootContext* ctx) override;
	void enterAbsolute_value(tsharp_parser::Absolute_valueContext* ctx) override;

	// Expressions
	void enterExpression(tsharp_parser::ExpressionContext* ctx) override;

	// Functions
	void enterFunction(tsharp_parser::FunctionContext* ctx) override;
	void enterFunc_call(tsharp_parser::Func_callContext* ctx) override;

	// OOP
	void enterClass(tsharp_parser::ClassContext* ctx) override;
	void enterObject_inst(tsharp_parser::Object_instContext* ctx) override;

	// Main function
	void enterMain_function(tsharp_parser::Main_functionContext* ctx) override;
	void exitMain_function(tsharp_parser::Main_functionContext* ctx) override;
};